SELECT * FROM TBCLIENTE;

SELECT CPF, NOME, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE,
SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TBCLIENTE;

SELECT CPF, NOME FROM TBCLIENTE;

SELECT CPF, NOME FROM tbcliente LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM TBCLIENTE;

SELECT NOME, CPF, SEXO, IDADE, DATA_NASCIMENTO FROM TBCLIENTE;


SELECT NOME, MATRICULA FROM tabela_de_vendedores;