USE TBPRODUTO;

ALTER TABLE TBPRODUTO ADD PRIMARY KEY (PRODUTO);

SELECT *FROM TBPRODUTO;

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

UPDATE TBPRODUTO SET EMBALAGEM  = "Garrafa"
WHERE PRODUTO = '1078680';