CREATE DATABASE SUCOS2;
USE SUCOS2;

create table tbCliente(
CPF VARCHAR(11),
NOME VARCHAR(150),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR (8), 
IDADE smallint,
SEXO VARCHAR (1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1));

create table tabela_de_vendedores(
MATRICULA VARCHAR (5),
NOME VARCHAR (100),
PORCENTUAL_COMISSAO FLOAT);

create table tbProduto(
PRODUTO VARCHAR (20),
NOME VARCHAR (150),
EMBALAGEM VARCHAR (50),
TAMANHO VARCHAR (50),
SABOR VARCHAR (50),
PRECO_LISTA FLOAT);

drop table tbcliente2;




